apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: person-names-deployment
spec:
  selector:
    matchLabels:
      app: person-names-app
  replicas: 1
  template:
    metadata:
      labels:
        app: person-names-app
    spec:
      containers:
        - name: person-names-app
          image: k8sexample/person-names-service
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
              name: server
