apiVersion: v1
kind: Service
metadata:
  name: person-names-db
  labels:
    app: person-names-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: person-names-db
  type: NodePort
